package com.vitran.backend.model.enums;

public enum LoginPermission {
    VIEW_ORDERS,
    CREATE_AND_UPDATE_ORDERS,
    VIEW_PERMISSIONS,
    CREATE_AND_UPDATE_PERMISSIONS,
    VIEW_CONSUMERS,
    CREATE_AND_UPDATE_CONSUMERS,
    VIEW_WORKERS,
    CREATE_AND_UPDATE_WORKERS,
    VIEW_ADMINS,
    CREATE_AND_UPDATE_ADMINS
}
